apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      nodePort: 30001
      targetPort: 8080
  selector:
    app: jenkins